Fix interactions
stopsack/risks pull request #20
Opened 2023-06-08 04:49 UTC by tgerke

I believe the function should work as intended now. i.e. we should be able to drop right in instead of the `any` block in
```
    interaction = any(
      grepl(
        pattern = ":",
        x = grep(
          pattern = paste0("^", predictor_replaced),
          x = names_effects,
          value = TRUE))) |
      any(grepl(
        pattern = paste0(":", predictor_replaced),
        x = names_effects,
        fixed = TRUE)))
```
but I'm not sure which of `predictor_replaced` or `predictor` should be fed to it?

2023-06-08 23:25 UTC, stopsack requested changes

2023-06-08 23:25 UTC, stopsack commented on R/margstd_variable.R
Looks great. `expsosure` -> `exposure`. 

I think `predictor_replaced` in `risks:::find_margstd_exposure()` gets rid of parentheses primarily for things like `as.factor()`. Not sure if needed.

This edge case works as expected:
```r
> has_exp_interaction(
+     glm(formula = death ~ as.factor(stage) * receptor, 
+         data = risks::breastcancer, 
+         family = binomial),
+     expsosure = "stage")
[1] TRUE
```

Works as expected too:
```r
has_exp_interaction(
+     glm(formula = death ~ stage * receptor, 
+         data = risks::breastcancer, 
+         family = binomial),
+     expsosure = "receptor")
[1] TRUE
```

This one should be `TRUE` too:
```r
> has_exp_interaction(
+     glm(formula = death ~ as.factor(stage) * receptor + var3, 
+         data = risks::breastcancer |> 
+             dplyr::mutate(var3 = rep(1:2, times = n() / 2)), 
+         family = binomial),
+     expsosure = "stage")
[1] FALSE
```

?
```r
> has_exp_interaction(
+  glm(formula = death ~ as.factor(stage) * receptor, 
+          data = risks::breastcancer |> 
+              dplyr::mutate(var3 = rep(1:2, times = n() / 2)), 
+          family = binomial),
+  expsosure = "stage")
[1] FALSE
```

2023-06-09 22:01 UTC, tgerke commented on R/margstd_variable.R
awesome catches, should be all set with the latest push. I also wrote in unit tests with your above examples which are good ones.

2023-06-10 12:13 UTC, stopsack requested changes
Great!
```r
> has_exp_interaction(
+     glm(
+         formula = death ~ age*receptor + receptor*as.factor(stage),
+         data = risks::breastcancer %>%
+             dplyr::mutate(age = sample(50:90, replace = TRUE, size = dplyr::n())),
+         family = binomial
+     ),
+     exposure = "stage"
+ )
[1] TRUE
```
Not so great - and who knows what else besides `as.numeric` a user might supply:
```r
> has_exp_interaction(
+     glm(
+         formula = death ~ age * receptor + receptor * as.numeric(as.factor(stage)),
+         data = risks::breastcancer %>%
+             dplyr::mutate(age = sample(50:90, replace = TRUE, size = dplyr::n())),
+         family = binomial
+     ),
+     exposure = "stage"
+ )
[1] FALSE
```

2023-06-13 12:59 UTC, closed without merging